# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ques1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
import sys
#importing question 2 so the connection from the button can sync when pressed
from ques2 import *

#this is the timer displayed in the quiz
class Ui_ques1(QtWidgets.QWidget):
    def __init__(self, name):
        super().__init__()
        self.name = name
        self.count = 1800
        self.total = 0

    def setupUi(self, ques1):
        ques1.setObjectName("ques1")
        ques1.resize(1071, 678)
        self.centralwidget = QtWidgets.QWidget(ques1)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(300, 310, 471, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.R1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.R1.setObjectName("R1")
        self.verticalLayout.addWidget(self.R1)
        self.R2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.R2.setObjectName("R2")
        self.verticalLayout.addWidget(self.R2)
        self.B1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.B1.setObjectName("B1")
        self.verticalLayout.addWidget(self.B1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(320, 70, 431, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.T1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T1.sizePolicy().hasHeightForWidth())
        self.T1.setSizePolicy(sizePolicy)
        self.T1.setObjectName("T1")
        self.horizontalLayout.addWidget(self.T1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.T2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.T2.setObjectName("T2")
        self.horizontalLayout.addWidget(self.T2)
        ques1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ques1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 26))
        self.menubar.setObjectName("menubar")
        ques1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ques1)
        self.statusbar.setObjectName("statusbar")
        ques1.setStatusBar(self.statusbar)
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.ShowTime)
        self.timer.start(1000)
        self.retranslateUi(ques1)
        QtCore.QMetaObject.connectSlotsByName(ques1)

    def retranslateUi(self, ques1):
        _translate = QtCore.QCoreApplication.translate
        ques1.setWindowTitle(_translate("ques1", "Question 1"))
        self.label.setText(_translate("ques1", "Question 1: Climate change is causing flowers to change colours"))
        self.R1.setText(_translate("ques1", "True"))
        self.R2.setText(_translate("ques1", "False"))
        self.B1.setText(_translate("ques1", "Continue"))
        self.label_3.setText(_translate("ques1", "Name: "))
        self.label_4.setText(_translate("ques1", "Remaining Time: "))
        self.B1.clicked.connect(self.opques)
        self.B1.clicked.connect(ques1.close)
        
        #This is the time function
    def ShowTime(self):
        if self.count > 0:
            self.count = self.count - 1
        #total minutes
        S1 = str(self.count//60)
        #remaining seconds
        S2 = str(self.count%60)
        S3 = S1 + "." + S2
        self.T1.setText(str(self.name))
        self.T2.setText(str(S3))
        #this is to determine whether the user has gotten the question correct or not.
    def opques(self):
        if self.R1.isChecked() == True:
            self.total = self.total + 3
        if self.R2.isChecked() == True:
            self.total = self.total - 1

        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_ques2(self.name,self.count,self.total)
        self.ui.setupUi(self.queswin)
        self.queswin.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ques1 = QtWidgets.QMainWindow()
    ui = ques1.ui()
    ui.setupUi(ques1)
    ques1.show()
    sys.exit(app.exec_())